### PR TITLE
Adding conan packaging configuration

### PR DESCRIPTION
**Pull request by dimi309**
As discussed, this is it. The conan packaging configuration can be found in the /conan subdirectory. Locally, you can package the library like this:

```
cd nytl/conan
conan create nyorain/stable
```

This will create the package `nytl/master@nyorain/stable`

If you would like to package a specific version, you need to change line 6 of conan/conanfile.py to `version = "0.1"` for example before executing the above mentioned command. In that case, the package signature will be `nytl/0.1@nyorain/stable`

To publish the package on bintray, you need to get an account there. Then, you create a conan repository on bintray. The repository will have a URL which you can find out by clicking on a "set me up" button that appears on its details. Before publishing, add this url to your conan instance using:

`conan remote add nyorainrepo http://myrepository`

Also before publishing, create an entry for the package in the conan repository on bintray, called nytl:nyorain (if you don't do that, you can still publish the package but you will have trouble updating its details. I think this is a bug or something). You can then publish it, using the following command:

conan upload nytl/0.1@nyorain/stable -r"nyorainrepo" --all

Once the package is published, you can see online on its details a button which you can click on to request that it be included in the conan-center repository. That is a curated repository, of good quality packages, managed by the conan team. Make sure you mention that you are the library developer and you are not packaging somebody else's library. This will speed things up hopefully :)

If you have any questions, let me know.

### CODE REVIEW

**Comment by nyorain** [comment]
Looks good so far, thanks. Will merge this in a moment.
I published it [here](https://bintray.com/nyorain/nytl/nytl%3Anyorain/master%3Adev), does that look alright or anything wrong?
This is not too intuitive, i have to get used to it and read through the conan docs before i request something for the official repos, is that alright?

**Comment by nyorain** [comment]
Btw is the test package really needed? Or should it execute any (unit) tests?

**Comment by dimi309** [comment]
It looks good to me.
Conan is a distributed package manager. In theory you could also be running your own server (also distributed as open source). They have fairly recently gone to bintray and are making this effort with conan center to have a collection of packages that are guaranteed to work well. In that sense, the advantage of putting packages on conan center in my opinion is visibility and advice on how to perfect them, but I don't think that there is any urgency. In any case, the team seems to be pretty busy these days so the procedure might take a bit of time anyway depending on how they prioritise things.
test_package is required every time the packaging takes place. Some people like to put unit tests there, but the idea, at least the way I understand it, is to just make sure with the test that the package is usable. This is why in nytl's test package, I only include one header and create one object. Extensive unit tests might not even work in some situations. For example, my library also plays sound and I build my packages on travis-ci, which does not set up sound on its "virtual machines". Of course, best practices evolve, so when I try to publish one of my packages to conan center, the team might tell me that it's better to unit test more in test_package. I am not sure what is considered to be the best way at present.

**Comment by nyorain** [comment]
Ah, good to know. Then i will leave everything as it is for now.
When i find the time and motivation i might play around with conan integration for my other projects and when i feel like i know what's going on i will submit them to conan center, your explanation makes sense.

**Comment by dimi309** [comment]
Sounds good! Welcome to conan packaging 😄

**Pull request merged**
